name: Fly Deploy

on: [push]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  # validate:
  #   name: lint code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set Node.js 18.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x
  #     - name: Run install
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: install
  #     - name: Check code
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: check
  #     - name: Lint code
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: lint
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
